on:
  pull_request:
    branches:
      - main
name: Soft KFC
jobs:
  check-kfc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: contains(github.event.pull_request.body, 'kfc')
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your pull request! This workflow is made with :heart: by the KFC team.'
            })
